### ISSUE TITLE
[5.x] Field rules that have rules for each other cause an infinite loop

### ISSUE THREAD

**Issue by Romanavr** [solspace/craft3-freeform#1130]
**Describe the bug or issue you're experiencing**
Situation is similar to https://github.com/solspace/craft-freeform/issues/1125. And I guess I found where is the problem:
If you create two fields (the type is unimportant) and add rules (also no matter what kind of the rule) to each, then an endless loop occurs, which is caused by a 500 timeout. For example:
We have 2 fields
![изображение](https://github.com/solspace/craft-freeform/assets/3519951/d176d1b6-f080-4216-80fb-78f94d64a236)
And two rules:
![изображение](https://github.com/solspace/craft-freeform/assets/3519951/c3513ae3-959e-41be-8009-a07b53e6b2ee)
![изображение](https://github.com/solspace/craft-freeform/assets/3519951/5c3713a9-c67f-404d-9152-8f97cdbcc7d2)
Then we will catch a timeout due to an endless loop, example with XDebug on a video:
https://drive.google.com/file/d/1uv1c1mtfmZq2t6LQHnoJi2Ub07LghiXV/view?usp=sharing

**Steps to reproduce**
1. Create 2 fields
2. Create any rule for the first field, where the second field will be target
3. Create any rule for the second field, where the first field will be target
4. Timeout

**Expected behavior**
Shouldn't there be a timeout?

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.8.0
- Freeform Version: 5.1.2
- Freeform Edition: **Pro**
- Fresh Install or Upgrade: **Upgrade**

**Comment by kjmartens** [comment]
Sorry for the delay, and thank you for reporting this @Romanavr.

We'll work on a fix for this shortly. 🙂

**Comment by kjmartens** [comment]
This is now resolved in Freeform 5.1.6. 🙂  We no longer allow fields to be mapped back to fields they're already mapped to.

**Comment by Romanavr** [comment]
> This is now resolved in Freeform 5.1.6. 🙂 We no longer allow fields to be mapped back to fields they're already mapped to.

@kjmartens Sorry, but that must be a joke? 

Previously it was possible to map fields to each other, I just tested version "v4.1.15.1" and can do it here. Is this a downgrade feature?
There are situations in which I need to map field rules to each other, otherwise why did I create this ticket?

Please re-open the issue and do as it was before. This doesn't solve my problem at all.

**Comment by kjmartens** [comment]
Perhaps I am misunderstanding this change/issue. We can certainly reopen this issue and provide an alternative solution. 🙂

However, what is the use case for having field A show only if field B contains X, but only show field B if field A contains Y? How is this a possible configuration?

**Comment by Romanavr** [comment]
> Perhaps I am misunderstanding this change/issue. We can certainly reopen this issue and provide an alternative solution. 🙂
> 
> However, what is the use case for having field A show only if field B contains X, but only show field B if field A contains Y? How is this a possible configuration?

I'm talking not only about “contains”, but also about “does not contain”, and also not only about 2 fields, but also about the possible connection of several fields with and/or a rule with each other, okay?

In the Issue I showed these two fields as an example. In my real case this is used for various select & dropdown fields. 

There must be a misunderstanding, I'm not asking for a "foolproof" solution to prevent users from creating relationships between fields, I'm asking you to fix the root problem that causes the infinite loop in such case.

Thanks!

**Comment by gustavs-gutmanis** [comment]
@Romanavr we are supporting nested rules, meaning that it is possible to chain many conditions in succession. If field A hides field B, but field B also determines if you would show fields C and D, then hiding field A also hides C and D based on the chained rules.
This introduces recursive lookup of values of all rules which are relying on the outcome of the current rule.

When field A relies on field B, and field B relies on field A for determining showing/hiding, an endless loop happens, because the rule checks all rules that are based on the outcome of the current rule, and so it checks rules for B, which then checks all the rules which are based on it, which then looks into field A, ad infinitum.

While I appreciate that this is an issue for you and we are here to help, I do not appreciate the way you're talking to people. 
Maybe you have ideas on how to support nested rules and still be able to do cross-field rules?
