### ISSUE TITLE
Salesforce integration issue

### ISSUE THREAD

**Issue by rhysmatthew** [solspace/craft3-freeform#1370]
### What happened?

Hi there, wondering if you can help me with an issue I'm having using the Salesforce API integration. Posting here by the way as the support feature on the site doesn't seem to be working. 

We are pretty sure it's mostly set up as it needs to be on both the Craft/Freeform and Salesforce side. However there's some error logs which I'm struggling to make sense of. I was wondering if you at Freeform had come across the same errors. I'm still able to submit forms etc, but these have popped up in the logs which worries me as it could be failing for some users. 

The error: `"Salesforce: [{"message":"Session expired or invalid","errorCode":"INVALID_SESSION_ID"}] {"integration":{"id":5,"handle":"salesforce"}} []" `

Are you able to shed any light on this? I've been finding the forum posts quite unhelpful when googling this. The SF API has 'Relax IP Restrictions' already which is the main one to look for apparently.

Thanks,
Rhys.

### How can we reproduce this?

N/A

### Freeform Edition

Pro

### Freeform Version

5.3.5

### Craft Version

4.10.1

### When did this issue start?

Unsure

**Comment by gustavs-gutmanis** [comment]
Hey @rhysmatthew,
Sorry to hear you're running into issues.
Based on the error message it seems like the `access_token` you have is no longer valid. Freeform uses a `refresh_token` to fetch a new access token each time it expires, so this should not be happening.

One possible issue that comes to mind is that you might not have `Offline Access` scope set up for your Salesforce Connect App.

Would you please check if it is present?

[Here's a link](https://docs.solspace.com/craft/freeform/v5/integrations/salesforce/) to our Salesforce integration documentation, just in case you need to look up how to check the settings.

**Comment by rhysmatthew** [comment]
@gustavs-gutmanis thank you for your quick response, appreciate it. 

I've re-looked at the docs above, it seems that it is set up as it should be.

Strange how it's erroring at random points in the night. My test submissions seem to be all working as expected.

![Screenshot 2024-06-25 at 12 37 30](https://github.com/solspace/craft-freeform/assets/77306946/b3ecd2b6-7a24-417d-aee9-53b084d79bbe)

![Screenshot 2024-06-25 at 12 40 53](https://github.com/solspace/craft-freeform/assets/77306946/03e39be1-a46a-4613-acc5-eba4313a8bb4)

![Screenshot 2024-06-25 at 12 42 01](https://github.com/solspace/craft-freeform/assets/77306946/153b3182-9976-426a-b548-920438e1de19)

**Comment by gustavs-gutmanis** [comment]
Very strange indeed, would you be able to go to the `Settings > Integrations > CRM`, open your Salesforce integration and click `Re-Authorize`? Or if there is no `Re-Authorize` link, click the `Save` button instead?

**Comment by rhysmatthew** [comment]
Okay no problem, it is showing as authorized so just clicked 'Save'. I'll continue to monitor and update you if it's still having issues in 24 hours or so. 

We were having issues with it becoming un-authorized before, but I think this was a 'Relax IP Restrictions' misconfiguration which isn't happening now.

**Comment by gustavs-gutmanis** [comment]
Ok, fingers crossed. Let us know!

**Comment by kjmartens** [comment]
This should now be fixed in Freeform 5.5.0. Please check and see if that's the case for you. 🙂

**Comment by rhysmatthew** [comment]
Hey @gustavs-gutmanis - I've not had any errors flag up in the last 24 hours. Maybe it's a non-issue and won't happen again, I'll continue to monitor for the next few days but if I don't reply after that then please close this issue. 

Thanks again for your help.

**Comment by rhysmatthew** [comment]
@kjmartens just saw your reply. That's great that you've identified something that may be causing this. I'll update now 🙂

**Comment by gustavs-gutmanis** [comment]
@rhysmatthew 
Previously, I checked if the token has expired by checking the current time against that of the `issued_at` + `expires_in` of the token. Looking back at it, now it's clear that there was a possibility of a race condition, where there is a second left on the lifetime of a token, but a building a request and sending it using the token would take a second more, and the token would become invalid (or due to some latency in the network).

Now we have a buffer for the expiration time, and we check for its validity removing two minutes from the expiration time, so this should never happen again. Hopefully that was the issue here.

**Comment by rhysmatthew** [comment]
@gustavs-gutmanis thank you, good to know what the cause was and that even when it did error it was only a minimal bug. Appreciate you guys looking into it / fixing 👍

**Comment by rhysmatthew** [comment]
@gustavs-gutmanis - just following up as we are still getting these errors, it's becoming 'De-authorized' at certain times meaning our forms stop sending and I have to re-authorize it via. Integrations CRM and clicking to re-auth etc. Confused as to what's happening, whether it's on the plugin side or SF's API. I've updated to your latest plugin version fyi. 

![a](https://github.com/solspace/craft-freeform/assets/77306946/d79e9dfb-ed59-4cf3-85c5-1663d3fbaef7)
![b](https://github.com/solspace/craft-freeform/assets/77306946/99cff83e-7a2c-445a-9ee9-0ccdeedb228d)

**Comment by gustavs-gutmanis** [comment]
This must be on our side, I am looking into it. Thanks for reporting again and for the patience.

**Comment by mofman** [comment]
I suspect the token is being refreshed and is added to the db however is not used the for the final submission to Salesforce.

**Comment by gustavs-gutmanis** [comment]
Thanks @mofman for the input.

@rhysmatthew I found the issue. Turns out Salesforce and some other OAuth2.0 supporting integrations returned the `issued_at` time in milliseconds rather than seconds. Since there is no standard for `issued_at` - there are integrations which return the timestamp in seconds, or don't return it at all.
Now Freeform knows which returns which and is acting accordingly to adjust the expiration check. The problem should be solved.

I was able to reproduce it on my end, btw, and this fix fixed it for me.

**Comment by mofman** [comment]
@gustavs-gutmanis just tested fix/SFT-1221-oauth and its still broken. 

As I said to the Kelsey in a seperate email, the issue was never whether the token was being refreshed or not - I have tested with additional logging and can see the token was always being refreshed at the right time. 

 In our site we have a pattern of specifc users submitting twice 
- the first one fails
- user doesnt proceed the next page
- submission is stored in freefrom
- throws exception, no salesforce entry, no email notification, no success page
- seconds later user  clicks submit again and everything works perfectly 
- anyone submitting in the next hour will all process as normal

This clearly implies that the token is renewed during the first attempt but not used until the next submit

**Comment by gustavs-gutmanis** [comment]
Thank you @mofman, I will check again.
It is weird that in my testing, a failing access token worked fine as soon as it was refreshed.
I'll come back to you in a little while, after I get this sorted out.

**Comment by mofman** [comment]
No problem, feel free to contact me directly if you need me to test anything for you.

**Comment by gustavs-gutmanis** [comment]
@mofman would it be possible for you to test the latest change?
I have made sure that the refreshing of tokens happens before the client is being compiled.

I went through the whole flow and tested that the refreshed token is received when a client is compiled, so it should work now.

**Comment by mofman** [comment]
@gustavs-gutmanis yes that appears to be working in my testing, although I'll keep an eye on submissions coming through in next few hours to ensure that has fully resolved

**Comment by gustavs-gutmanis** [comment]
Thanks for the help, greatly appreciated!

**Comment by rhysmatthew** [comment]
@gustavs-gutmanis thanks for continuing to look into this. Currently having to re-auth in control panel each day at least once or twice to get working, but let me know if you guys reach a solution and I can update the plugin.

**Comment by rhysmatthew** [comment]
Just attaching recent logs if they're helpful at all. So yesterday late afternoon it was re-auth'd in control panel and it looks like at 5am this morning it dropped out again randomly.

![Screenshot 2024-06-27 at 11 52 16](https://github.com/solspace/craft-freeform/assets/77306946/eaa698c7-22e5-4938-bb2e-92b5bac3c4ce)

**Comment by mofman** [comment]
@rhysmatthew you can test latest fix by using this in composer.json if you want

`"solspace/craft-freeform": "dev-fix/SFT-1221-oauth as 5.5.0.1",`

**Comment by rhysmatthew** [comment]
@mofman thank you, I'll give this a try and see if the same problem persists 👍

**Comment by rhysmatthew** [comment]
@gustavs-gutmanis - just to update, I've had no issues with it becoming un-authorized since installing "dev-fix/SFT-1221-oauth as 5.5.0.1". So at this point, issue seems to be resolved. Thanks again.

**Comment by gustavs-gutmanis** [comment]
Thanks for letting us know!
