### ISSUE TITLE
Slug cannot be blank error on multipage form with entries integration

### ISSUE THREAD

**Issue by Coysh** [solspace/craft3-freeform#1388]
### What happened?

I have a multipage form which creates an entry on page 2.
If I try and submit page 1, I get the error "Slug cannot be blank".

Below are some screenshots of my setup.
![CleanShot 2024-07-01 at 16 56 36](https://github.com/solspace/craft-freeform/assets/5764356/d0732fe4-ae2f-4d5c-b713-c34cbe32fe38)
![CleanShot 2024-07-01 at 16 57 03](https://github.com/solspace/craft-freeform/assets/5764356/0bd4ebd6-bbb2-49b4-a4f5-e10cb2c189a8)

### How can we reproduce this?

1.  Create a multipage form
2.  Add Entries integration
3.  Put mapped fields on page 2

### Freeform Edition

Pro

### Freeform Version

5.3.1

### Craft Version

Latest

**Comment by gustavs-gutmanis** [comment]
Thanks for reporting this @Coysh, we found the issue and fixed it, it will be released in the upcoming release

**Comment by Coysh** [comment]
Hi @gustavs-gutmanis - I've pulled the fix into my local development area, which has fixed the error on this issue.
I'm having these issues now.. Unsure if they were there before.
![CleanShot 2024-07-02 at 17 09 13](https://github.com/solspace/craft-freeform/assets/5764356/0f278f65-c461-4ac3-ace0-4f111ede164c)
![CleanShot 2024-07-02 at 17 09 45](https://github.com/solspace/craft-freeform/assets/5764356/c0228d88-c25f-48c2-a343-ee5a538fb200)

**Comment by kjmartens** [comment]
Hi @Coysh,

The first part of this issue should be fixed now and available in Freeform 5.5.2. The other issue you describe is something that likely would have always existed. However, we'll build a transformer to handle sending Freeform data to the Craft URL field type and release another update soon. 🙂

**Comment by Coysh** [comment]
Hey @kjmartens - thanks for the update. Is the transformer a soon to be released item? Or will it take some time?

**Comment by kjmartens** [comment]
@Coysh likely today or tomorrow. 🙂

**Comment by Coysh** [comment]
Hi @gustavs-gutmanis  @kjmartens , Sorry to reopen an old issue - but I still have issues here and I am 5.5.4.
I have rules on this form.. They can select an existing entry, in which case the integration isn't needed - or they can enter in their own fields and create an entry.

If the user selects an existing entry, I still get this error
![CleanShot 2024-07-29 at 14 18 19](https://github.com/user-attachments/assets/f05ec3f1-b3a1-41f9-8c22-808e93b5375a)

**Comment by kjmartens** [comment]
Hi @Coysh,

Just to confirm, are you saying your form is supposed to follow two different behaviors based on user input?

So, you have a `Is your organization a member?` checkbox, which then shows/hides the **Find your organisation** field and **Organisation**, etc fields accordingly...

1. If a user checks off the `Is your organization a member?` checkbox and selects an existing entry in the **Find your organisation** field, it should relate the submission to the selected Craft entry and ignore mapping/creating a new Craft entry (the Entry integration mapping set up in the builder).
2. If a user does not check off the `Is your organization a member?` checkbox, they proceed to filling out the form and creating a new Craft entry (as mapped in the form builder).

Is this correct?

If so, this is not a bug. It's a flow that is currently not accounted for (and I am not sure how feasible it is either). If you have an Entry integration enabled and mapped for the form in the builder, Freeform expects to create it and validate against it. There is no way to override this behavior at the template level.

I can check with @gustavs-gutmanis to see how complex this would be to support and get back to you. 🙂
