### ISSUE TITLE
Unable to View Submissions after Upgrade Freeform 5.0.x.x

### ISSUE THREAD

**Issue by phillipsandoveracademy** [solspace/craft3-freeform#999]
**Describe the bug or issue you're experiencing**
Might be two issues:

Issue 1
Upgraded successfully from Freeform 4.1.13 to 5.0.4. Unable to view submissions. I get DB errors when trying to view any form submissions. See photo below. Should past submissions still show?

Issue 2
Also, I tested on form and it appeared to submit correctly. I was then able to view the submission list for the form, but opening an old submission, the submission was blank. Data appears to be missing? Is this expected? For the test submission made with Freeform 5.0.4, data was present.

**Steps to reproduce**

1. Freeform -> Submissions
2. Select form to view submissions. Server error occurs.

**Expected behavior**
View past submissions as before.

**Craft & Plugin Info (please complete the following information):**

- Craft Version: 4.7.0
- Freeform Version: 5.0.4
- Freeform Edition: Pro
- Fresh Install or Upgrade: Upgrade from Freeform 4.1.13

**Additional context**
![Screenshot 2024-01-30 at 3 23 35 PM](https://github.com/solspace/craft-freeform/assets/11964584/aab39caf-9333-411e-b868-5bcc53756708)
Issue 1: Error when trying to view form submissions.
![Screenshot 2024-01-30 at 3 31 59 PM](https://github.com/solspace/craft-freeform/assets/11964584/666bdf1e-9800-44b2-bb44-10bf1baa8855)
Issue 2: Form submission listing for form I tested on Freeform 5.0.4.
![Screenshot 2024-01-30 at 3 31 32 PM](https://github.com/solspace/craft-freeform/assets/11964584/f639b726-953f-4396-9673-2fc6ed497454)
Issue 2: Past form submission under Freeform 4.1.13 or earlier. Data is not present in submission.
![Screenshot 2024-01-30 at 3 32 14 PM](https://github.com/solspace/craft-freeform/assets/11964584/6dfc0f39-514f-4e3d-b0b6-39a93f6a79e5)
Issue 2: Form submission using Freeform 5.0.4. Data appears in submission.

**Comment by kjmartens** [comment]
Sorry for the trouble you're experiencing @phillipsandoveracademy,

Can you confirm... did you upgrade directly to `5.0.4`? Or did you update to a previous version (and eventually update to 5.0.4)? 🙂 

And did any errors happen during the migration?

**Comment by phillipsandoveracademy** [comment]
@kjmartens ... Yes. I did an upgrade from Freeform 4.1.3 to 5.0.4 on my local machine with a clean production DB. There were no errors with migration. Unlike the previous time upgrading, the migrations did not print out. Once the upgrade was complete, it just said the migrations were done. See photo: 
![Screenshot 2024-01-31 at 8 48 20 AM](https://github.com/solspace/craft-freeform/assets/11964584/cd15f1ac-8fda-4f32-8a74-61e9b0a42dcf)
Hope this is helpful!

**Comment by kjmartens** [comment]
Thanks @phillipsandoveracademy.

Weird the migrations didn't show up. Just to confirm, if you do `php craft migrate/all` does anything show up?

**Comment by phillipsandoveracademy** [comment]
Hi @kjmartens ... Thanks for your reply. If I upgrade with `php craft update freeform`, I do not see any migrations, even if I run `php craft migrate/all`. I only see the migrations if I manually update the composer file and run `composer update`. See image below.

![020124__FreeForm5061__update](https://github.com/solspace/craft-freeform/assets/11964584/cd92d4b5-e360-4ca3-b54c-4b77d005311f)
`composer update` migrations. The above image is upgrading from Freeform 4.1.3 to Freeform 5.0.6.1.

With the new version of Freeform 5.0.6.1, I am still not able to see form submissions that occurred from Freeform 4.1.13 or earlier. See below images.

![Screenshot 2024-02-01 at 4 34 12 PM](https://github.com/solspace/craft-freeform/assets/11964584/c74f6a5a-5945-4d5e-8693-a1d3e4a8c470)
![Screenshot 2024-02-01 at 4 18 28 PM](https://github.com/solspace/craft-freeform/assets/11964584/cf0af57b-b262-497a-9174-3b4d9dcbab74)
The error regardless of which form submissions selected is `PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column`. Again, I am not sure if I am missing something I need to do before migrating to Freeform 5 or something else.

**Comment by kjmartens** [comment]
Thanks for all the info, @phillipsandoveracademy.

If you resave an affected form in the form builder, does the Submissions index page begin to work / not error anymore? And if so, I assume that upon closer inspection, data will have shifted incorrectly among some fields. Can you see if that's the case? 🙂

**Comment by phillipsandoveracademy** [comment]
@kjmartens ... Yes. If I resave the form, I am able to see the Submissions page for that form. Though, the data for each submission is missing. The submissions were made for Freeform 4.1.3 or earlier.

![Screenshot 2024-02-01 at 5 04 17 PM](https://github.com/solspace/craft-freeform/assets/11964584/fbf4cd65-80c0-47d5-8cb5-4657d7553436)
![Screenshot 2024-02-01 at 5 04 44 PM](https://github.com/solspace/craft-freeform/assets/11964584/b454caae-290d-4ae1-bee2-ad3c27895274)

**Comment by kjmartens** [comment]
Thanks for that. There certainly must be something in your data/structure that the migration is choking on.

Can you send me the table structure for the Submissions table of this form when it was in v4, before the upgrade, and then what it looks like after the upgrade (before saving the form)?

I'm also curious what kind of content was in there... perhaps even a screenshot of the database table content with the columns and some field data showing. 🙂

**Comment by phillipsandoveracademy** [comment]
Hi @kjmartens ... I have attached three photos of the DB. I am using one of our example forms, Athletics Hall of Honor. First photo is Freeform 4.1.13. Second photo is Freeform 5.0.6.1 before I save the form. Third photo is Freeform 5.0.6.1 after I save the form. As you can see, the DB form fields change after I save the form in Freeform 5. Each form after it is saved in Freeform 5 can either loose all of the data in the form fields or partially. This example below shows partial loss of data in form fields after save. I hope this is helpful. I am blurring data to ensure security of field data, but I hope this is enough to show the issue we are experiencing. 
![Screenshot 2024-02-02 at 10 20 11 AM__edit__freeform413](https://github.com/solspace/craft-freeform/assets/11964584/ca873184-ed74-44d6-8da8-c8fd9ba56cd9)
Freeform 4.1.13
![Screenshot 2024-02-02 at 10 25 35 AM__edit__freeform5061__beforeFormSave](https://github.com/solspace/craft-freeform/assets/11964584/3a6950b1-4749-4df5-84d2-093b0f0c2b93)
Freeform 5.0.6.1 before form save
![Screenshot 2024-02-02 at 10 29 19 AM__edit__freeform5061__afterFormSave](https://github.com/solspace/craft-freeform/assets/11964584/9e7cb408-0bb6-4cd8-844d-773ff821fd21)
Freeform 5.0.6.1 after form save

**Comment by kjmartens** [comment]
Thanks for this @phillipsandoveracademy. We will continue to investigate this issue.

Thank you for your patience.

**Comment by gwillz** [comment]
We've also encountered this behaviour. We've reverted production to a backup, but we can reproduce this on our local environments quite consistently. Let me know if there's anything we provide to help!

**Comment by seandelaney** [comment]
@phillipsandoveracademy 

I'm struggling to replicate your issue. I've tested multiple Freeform 4 to Freeform 5 upgrades using all sorts of setups, ranging from complex forms/fields to simple forms/fields and migrations ran successfully every time. Whether its via CLI or CP Plugin screen. I can view the forms, fields and submissions afterwords.

I don't like how the migrations didn't print out the first time you tried to upgrade. 

Personally, I would have backed up the DB before running any upgrades. I see you skipped that step.

Question - When you updated composer.json and ran composer update the second time to attempt upgrading again, I see the migrations printed out but was this done on a restored DB or the same DB again?

Question - What PHP version are you running?

Same for @gwillz  - What PHP version are you running?

Sending me a DB backup would help me try and identify any potential migration issues. Clear all entries, users, categories and Freeform submissions etc so the DB backup only has your Freeform forms, fields etc.

Email: sean@solspace.com

In the mean time, I will continue to investigate.

Thanks

**Comment by johnnymueller** [comment]
@seandelaney I'm experiencing the same issues. I'm on PHP 8.0, mariadb 10.4.

I initially ran the update through the Craft control panel. I wasn't able to view submissions so tried re-saving the form. After that I was able to view submissions but most fields were missing and some were shifted (name showing up under the email field, etc.). I tried downgrading Freeform to v4 and restored the db to my pre-upgrade backup. Ran through the update process in the command line and didn't see any migrations.

One thing worth noting is when trying to re-save forms I got some errors around handles. One error I saw was "Value contains 159 characters, 100 allowed" for a field handle. Another form wasn't letting me use hyphens for a multi-word form handle.

I'm going to try another run through just to make sure I didn't miss anything. I'll email you a DB backup if I'm still running into issues.

**Comment by johnnymueller** [comment]
Update: I'm able to see migrations in the terminal if I update composer.json, delete composer.lock and run `composer install`, then `craft migrate --plugin=freeform`.

If I fix the form handle that was causing issues as mentioned above, I'm able to see the list of submissions after running through this process, but individual submissions throw a database exception. Fixing field handles does not improve anything and I'm not able to see the submission list view.

I'm using ddev for local development, btw.

**Comment by seandelaney** [comment]
@phillipsandoveracademy @gwillz 

Are you guys able to send me a DB backup and answer which PHP version you are running?

@gwillz 

By any chance are you running DDEV with MariaDB as your DB? If so, then this might be your issue as MariaDB is not supported anymore within the DDEV env. 

See: https://craftcms.com/knowledge-base/craft-database-options-and-best-practices#mariaDB

I've submitted a [PR increasing the character limit on a field handles](https://github.com/solspace/craft-freeform/pull/1048).

**Comment by gwillz** [comment]
Our initial run-in with this one was on a production environment so I can't share the whole thing. I've taken some samples instead of the affected database and scrubbed anything sensitive. See if anything there helps.

We do have a lot of installs of freeform on different clients so if you need more I might be able to replicate it elsewhere.

We're not running DDEV but we do run containerized versions of PHP 8.1 and MariaDB 10.6. However the production box is a bare AWS EC2 running the same versions.

[freeform-4-to-5.txt](https://github.com/solspace/craft-freeform/files/14252694/freeform-4-to-5.txt)

**Comment by phillipsandoveracademy** [comment]
@seandelaney 

Thanks for the questions. My apologies for responding 5 days late. 

All of my work is done on my local machine, so I can backup PROD DB anytime, which is why I just normally skip the DB backup process. I can restore to a clean DB quickly on my local machine.

I used a clean PROD DB backup when running `composer update`, when I saw the migrations print out. For some reason, the print out did not occur running `php craft update`. Though, the result for both updates were the same and had the same issues.

I am using DDEV locally, running php 8.0.

Hope this is helpful!

**Comment by kjmartens** [comment]
Thanks for the additional information @gwillz and @phillipsandoveracademy. We are making progress with pinpointing some of the issues affecting the migration and hope to have an update very soon. 🙂

**Comment by kjmartens** [comment]
Thanks for your patience @phillipsandoveracademy, @gwillz, and @johnnymueller.

We believe we have finally addressed all the issues with the migration script in Freeform 5.0.11.

Please let us know if you are still seeing any issues. 🙂

**Comment by johnnymueller** [comment]
@kjmartens I just upgraded to 5.0.12 and am still experiencing incorrect column suffixes after running the migrations.
<img width="1592" alt="Screenshot 2024-02-21 at 9 36 09 AM" src="https://github.com/solspace/craft-freeform/assets/369241/43a4b275-707d-4aed-ac72-ed41d15a460c">

**Comment by kjmartens** [comment]
@johnnymueller was this a fresh update from Freeform 4.x directly to 5.0.12? That's what it will need to be since the fix is in the migration and it's not retroactive if you update from 5.0.10 to 5.0.12, etc.

**Comment by johnnymueller** [comment]
@kjmartens Yes, this was from a fresh DB at Freeform 4.x directly to 5.0.12.

**Comment by kjmartens** [comment]
@johnnymueller we just released another update to the migration script. Can you try upgrading from Freeform 4.x to 5.0.14.1 when you get the chance? 🙂

**Comment by johnnymueller** [comment]
@kjmartens @seandelaney 5.0.14.1 worked! Thanks for sticking with me to get this figured out!

**Comment by niklasjk** [comment]
I'm still running into this issue. I tried the suggested action and everything else works now except for the "All Submissions"-view. Should it be a specific 4.x version or is there something else I could try?

**Comment by seandelaney** [comment]
@niklasjk 

Can you please confirm that you used a clean DB backup, and not attempting to re-run update migrations on an previously failed updated migrated DB? 
Did you see all the migrations print out?
Any errors in there?
Do you have any other migrations pending? Craft or other plugins?

The version of Freeform 4 shouldn't make a different. When you attempt to update to Freeform 5, all pending/new migration scripts will be ran.

**Comment by niklasjk** [comment]
Yes, clean DB backup. I tested it again now and it's still the same result. It looks like the migrations all run correctly but now when I looked at it a bit more closely I noticed that one of the submissions tables in the database had the "old_xxx" column names, so that particular migration hadn't run for that table. I didn't see any errors though or any pending migrations.

**Comment by seandelaney** [comment]
@niklasjk 

Can you please email me a DB backup containing only the freeform tables. So delete all entries, users, globals etc and remove any sensitive data. I will take a look. 

sean@solspace.com

Thanks

**Comment by seandelaney** [comment]
@niklasjk I have fixed your issue.

PR open. https://github.com/solspace/craft-freeform/pull/1134
